/**
 * What a native reading's HTML may contain once ingested (ADR-0002 §Readings on the app origin).
 * The server sanitises with `readingSchema` (`apps/server/src/content/reading.ts`) and then adds
 * block, figure and image ids; the browser sanitises again with this list before the HTML is
 * inserted on the app origin. A unit test holds the two layers to the same list, so widening one
 * means widening both. Names are HTML attribute names (`class`, `aria-label`), not hast props.
 */

const ARIA = ['aria-describedby', 'aria-label', 'aria-labelledby'];

/** MathML that KaTeX emits (`output: 'mathml'`), and its presentation attributes. */
const MATHML_TAGS = [
  'math',
  'annotation',
  'semantics',
  'menclose',
  'merror',
  'mfrac',
  'mi',
  'mn',
  'mo',
  'mover',
  'mpadded',
  'mphantom',
  'mroot',
  'mrow',
  'ms',
  'mspace',
  'msqrt',
  'mstyle',
  'msub',
  'msubsup',
  'msup',
  'mtable',
  'mtd',
  'mtext',
  'mtr',
  'munder',
  'munderover',
];
const MATHML_ATTRIBUTES = [
  'accent',
  'accentunder',
  'columnalign',
  'columnlines',
  'columnspacing',
  'depth',
  'display',
  'displaystyle',
  'encoding',
  'fence',
  'height',
  'largeop',
  'linebreak',
  'linethickness',
  'lspace',
  'mathbackground',
  'mathcolor',
  'mathsize',
  'mathvariant',
  'maxsize',
  'minsize',
  'movablelimits',
  'notation',
  'rowlines',
  'rowspacing',
  'rspace',
  'scriptlevel',
  'separator',
  'stretchy',
  'symmetric',
  'voffset',
  'width',
];

export const READING_HTML_TAGS: readonly string[] = [
  'a',
  'b',
  'blockquote',
  'br',
  'caption',
  'code',
  'col',
  'colgroup',
  'dd',
  'del',
  'details',
  'div',
  'dl',
  'dt',
  'em',
  'figcaption',
  'figure',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'hr',
  'i',
  'img',
  'input',
  'ins',
  'kbd',
  'li',
  'ol',
  'p',
  'pre',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'section',
  'span',
  'strike',
  'strong',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'tr',
  'tt',
  'ul',
  'var',
  ...MATHML_TAGS,
];

/**
 * Allowed attributes per element; `*` applies to every element. Ids, names and aria references
 * carry the `user-content-` prefix; URLs are limited by `READING_HTML_PROTOCOLS`.
 */
export const READING_HTML_ATTRIBUTES: Readonly<Record<string, readonly string[]>> = {
  '*': [
    'abbr',
    'accept',
    'accept-charset',
    'accesskey',
    'action',
    'align',
    'alt',
    'axis',
    'border',
    'cellpadding',
    'cellspacing',
    'char',
    'charoff',
    'charset',
    'checked',
    'clear',
    'colspan',
    'color',
    'cols',
    'compact',
    'coords',
    'datetime',
    'dir',
    'enctype',
    'frame',
    'hspace',
    'headers',
    'height',
    'hreflang',
    'for',
    'id',
    'ismap',
    'itemprop',
    'label',
    'lang',
    'maxlength',
    'media',
    'method',
    'multiple',
    'name',
    'nohref',
    'noshade',
    'nowrap',
    'open',
    'prompt',
    'readonly',
    'rev',
    'rowspan',
    'rows',
    'rules',
    'scope',
    'selected',
    'shape',
    'size',
    'span',
    'start',
    'summary',
    'tabindex',
    'title',
    'usemap',
    'valign',
    'value',
    'width',
    // Added after sanitising: the anchor and figure ids of ADR-0003.
    'data-block-id',
    'data-figure-id',
  ],
  a: [...ARIA, 'data-footnote-backref', 'data-footnote-ref', 'class', 'href', 'rel'],
  blockquote: ['cite'],
  code: ['class'],
  del: ['cite'],
  // `class` is the display-math block (`math-display`), set after sanitising.
  div: ['itemscope', 'itemtype', 'class'],
  dl: ARIA,
  h2: ['class'],
  // `data-object-key` names the uploaded file; the server turns it into `src` at read time.
  img: ['alt', 'src', 'title', 'data-object-key'],
  input: ['disabled', 'type'],
  ins: ['cite'],
  li: ['class'],
  ol: [...ARIA, 'class'],
  q: ['cite'],
  section: ['data-footnotes', 'class'],
  span: ['class'],
  summary: ARIA,
  table: ARIA,
  ul: [...ARIA, 'class'],
  ...Object.fromEntries(MATHML_TAGS.map((t) => [t, MATHML_ATTRIBUTES])),
};

/**
 * Class names each element may carry (a string, or a pattern for a whole class name); others are
 * dropped from the attribute. `div`'s is the display-math block, set after sanitising.
 */
export const READING_HTML_CLASSES: Readonly<Record<string, readonly (string | RegExp)[]>> = {
  a: ['data-footnote-backref'],
  code: [/^language-./, 'hljs'],
  div: ['math-display'],
  h2: ['sr-only'],
  li: ['task-list-item'],
  ol: ['contains-task-list'],
  section: ['footnotes'],
  span: [/^hljs-[a-z_-]+$/, 'katex'],
  ul: ['contains-task-list'],
};

/** The `rel` values ingestion gives outbound links. */
export const READING_LINK_REL: readonly string[] = ['noopener', 'noreferrer', 'nofollow'];

/** Schemes each URL attribute may use; a URL with no scheme (relative, `#…`) is allowed. */
export const READING_HTML_PROTOCOLS: Readonly<Record<string, readonly string[]>> = {
  href: ['http', 'https', 'irc', 'ircs', 'mailto', 'xmpp'],
  src: ['http', 'https'],
  cite: ['http', 'https'],
};

/** The prefix ids, names and id references carry, so reading markup cannot clobber app names. */
export const READING_ID_PREFIX = 'user-content-';
